In [16]:
import pandas as pd

data = pd.read_excel("/content/enflasyon.xlsx")

data.head()

     Date   TÜFE (Yıllık % Değişim)  TÜFE (Aylık % Değişim)
0  03-2022                    61.14                    5.46
1  02-2022                    54.44                    4.81
2  01-2022                    48.69                   11.10
3  12-2021                    36.08                   13.58
4  11-2021                    21.31                    3.51

In [22]:
data = pd.read_excel("/content/enflasyon.xlsx" ,sheet_name="Sayfa2")

data.head()

  Boş Sayfa Boş Sayfa.1 Boş Sayfa.2
0      Test        Test        Test
1      Test        Test        Test
2      Test        Test        Test
3      Test        Test        Test
4      Test        Test        Test

In [4]:
data = pd.read_excel("/content/enflasyon.xlsx" , header=None)

data.head()

         0                        1                       2
0    Date   TÜFE (Yıllık % Değişim)  TÜFE (Aylık % Değişim)
1  03-2022                    61.14                    5.46
2  02-2022                    54.44                    4.81
3  01-2022                    48.69                    11.1
4  12-2021                    36.08                   13.58

In [5]:
data = pd.read_excel("/content/enflasyon.xlsx" , index_col = 0)

data.head()

         TÜFE (Yıllık % Değişim)  TÜFE (Aylık % Değişim)
Date
03-2022                    61.14                    5.46
02-2022                    54.44                    4.81
01-2022                    48.69                   11.10
12-2021                    36.08                   13.58
11-2021                    21.31                    3.51

In [26]:
data = pd.read_excel("/content/enflasyon.xlsx")

data.head()

     Date   TÜFE (Yıllık % Değişim)  TÜFE (Aylık % Değişim)
0  01-2005                     9.24                    0.55
1  02-2005                     8.69                    0.02
2  03-2005                     7.94                    0.26
3  04-2005                     8.18                    0.71
4  05-2005                     8.70                    0.92

In [27]:
data = pd.read_csv("/content/USD_TRY.csv")
data.head()

        Tarih    Şimdi   Açılış   Yüksek    Düşük Fark %
0  31.12.2021  13,3161  13,1514  13,6993  12,9045  1,31%
1  30.12.2021  13,1440  12,6357  13,5264  12,3795  4,02%
2  29.12.2021  12,6359  11,8049  12,7776  11,7685  7,10%
3  28.12.2021  11,7978  11,6822  12,0285  11,5030  1,01%
4  27.12.2021  11,6801  10,7513  11,8656  10,6654  9,69%

In [30]:
data = pd.read_csv("/content/USD_TRY.csv", skiprows = [1,2,3], header=0)
data.head()

        Tarih    Şimdi   Açılış   Yüksek    Düşük  Fark %
0  28.12.2021  11,7978  11,6822  12,0285  11,5030   1,01%
1  27.12.2021  11,6801  10,7513  11,8656  10,6654   9,69%
2  24.12.2021  10,6480  11,3912  12,3187  10,3632  -6,63%
3  23.12.2021  11,4040  11,9946  12,3665  10,1565  -4,83%
4  22.12.2021  11,9825  12,4331  12,8375  11,9650  -3,62%